[package]
name = "prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
random_color = "0.6.1"
tokio = { version = "1.30.0", features = ["full"]}
futures = "0.3.28"
